baseURL = "https://side-realms.github.io"
title = "no Sound"
paginate = 5
theme = "PaperMod"
publishDir = "docs"
# defaultContentLanguage = "en"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "G-MY_ID"

[minify]
disableXML = true
minifyOutput = true

[params]
title = "no Sound"
description = "mypage"
keywords = [ "shanpu", "portal", "Blog", "Portfolio" ]
# author = "Kohei Doi"
DateFormat = "1999"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/side_realms"

  #[[params.socialIcons]]
  #name = "github"
  #url = "https://github.com/chez-shanpu"

  #[[params.socialIcons]]
  #name = "linkedin"
  #url = "https://www.linkedin.com/in/tomoki-sugiura/"

[languages.en]
languageName = "English"
weight = 1
contentDir = "content"
staticDir = "static/"

  [languages.en.profileMode]
  enabled = true
  title = "You like music? 🦑"
  subtitle = "Let me know if you have any good tunes!"
  imageUrl = "/images/icon.jpg"
  imageWidth = 360
  imageHeight = 360
  imageTitle = "myicon"

    #[[languages.en.profileMode.buttons]]
    #name = "aa"
    #url = "aa"

    #[[languages.en.profileMode.buttons]]
    #name = "aa"
    #url = "blogs/"

[[languages.en.menu.main]]
name = "Treasure Trove"
url = "treasure/treasure"
weight = 5


[[languages.en.menu.main]]
name = "Portfolio"
url = "portfolio/portfolio"
weight = 8


[[languages.en.menu.main]]
name = "resource"
url = "resource"
weight = 10


#[languages.en.menu.main]]
#name = "study log"
#url = "log"
#weight = 15

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  endLevel = 2
  ordered = true
  startLevel = 1


#[languages.en]
#languageName = "English"
#weight = 2
#contentDir = "content/en"
#staticDir = "static/"
#
#  [languages.en.profileMode]
#  enabled = true
#  title = "shanpu portal"
#  subtitle = "Cloud Native Student"
#  imageUrl = "images/shanpu-profile.JPG"
#  imageWidth = 120
#  imageHeight = 120
#  imageTitle = "shanpu-profile"
#
#    [[languages.en.profileMode.buttons]]
#    name = "About Me"
#    url = "en/about"
#
#    [[languages.en.profileMode.buttons]]
#    name = "Blog"
#    url = "en/blogs"
#
#[[languages.en.menu.main]]
#name = "About Me"
#url = "en/about/"
#weight = 5
#
#[[languages.en.menu.main]]
#name = "Blog"
#url = "en/blogs/"
#weight = 10
